### Pandas

In [126]:
import pandas as pd
import numpy as np

In [127]:
a = [1,2,3,4,5]
s = pd.Series(a)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [128]:
s = pd.DataFrame(a)
s

   0
0  1
1  2
2  3
3  4
4  5

In [129]:
df = pd.read_csv("../employees_100.csv")
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [130]:
df[df.isna().any(axis=1)].tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
80,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
81,185,Vikram Desai,NaN,Pune,39.0,68197,9,4,9,2024-09-13
91,175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [131]:
df[['name','salary','department']].tail()

           name salary department
95  Nikhil Nair  55740  MARKETING
96   Neha Desai  52250         HR
97   Neha Reddy    NaN  Marketing
98  Priya Nayak  56821         HR
99  Kavya Joshi  69499  Marketing

In [132]:
df.iloc[0:5]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [133]:
df[(df['department'] == 'Finance') & (df['age'] > 40)]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09

In [134]:
df.dropna()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...,...
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [135]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [136]:
df.dropna( subset =['salary','age'])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
...,...,...,...,...,...,...,...,...,...,...
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [137]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [138]:
df['age'].fillna(df['age'].mean(), inplace = True)

C:\Users\hp\AppData\Local\Temp\ipykernel_26576\121903411.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace = True)

In [139]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [140]:
df['salary'] = df['salary'].str.replace(",","",regex=False)
df['salary'] = pd.to_numeric(df['salary'],errors='coerce')
df['salary'] = df['salary'].fillna(df['salary'].median())

In [141]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [142]:
df['department'].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [143]:
df['department'].dtype

dtype('O')

In [144]:
df['department'] = df['department'].fillna(df['department'].mode()[1])
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [145]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [146]:
df['department'].value_counts()

department
Marketing       25
HR              17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [147]:
df.duplicated().sum()

np.int64(0)

In [148]:
df.duplicated(subset='department').sum()

np.int64(87)

In [149]:
df = df.reset_index()

In [150]:
df

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05
2,2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
4,4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...,...
95,95,161,Nikhil Nair,MARKETING,Chennai,22.000000,55740.0,0,5,22,2020-04-22
96,96,172,Neha Desai,HR,Chennai,22.000000,52250.0,0,5,7,2020-11-14
97,97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06
98,98,193,Priya Nayak,HR,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07
99,99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25

In [151]:
df.duplicated(subset='employee_id').sum()

np.int64(4)

In [152]:
df[df.duplicated(subset=['employee_id'], keep=False)].sort_values('employee_id')

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
13,13,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422.0,3,6,12,2021-11-24
69,69,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422.0,3,6,13,2021-11-24
74,74,158,Tanvi Malhotra,Marketing,Mumbai,32.0,88366.0,11,5,19,2021-02-26
75,75,158,Tanvi Malhotra,Marketing,Mumbai,32.0,88366.0,11,6,17,2021-02-26
27,27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273.0,5,6,11,2020-09-05
68,68,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273.0,5,7,11,2020-09-05
61,61,164,Sneha Gupta,Marketing,Delhi,42.0,63209.0,11,3,8,2021-08-07
80,80,164,Sneha Gupta,Marketing,Delhi,42.0,63209.0,11,4,7,2021-08-07

In [153]:
df.drop_duplicates(subset='employee_id', keep='first',inplace=True)

In [154]:
# df.duplicated(subset='employee_id').sum()
# df.duplicated(subset='employee_id').sum()

In [155]:
df['joining_date'].dtype

dtype('O')

In [156]:
df['joining_date'] = pd.to_datetime(df["joining_date"])

In [157]:
df['joining_date'].dtype

dtype('<M8[ns]')

In [158]:
df.rename(columns = {"Full_Name":"name"},inplace =True)

In [159]:
df

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05
2,2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
4,4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...,...
95,95,161,Nikhil Nair,MARKETING,Chennai,22.000000,55740.0,0,5,22,2020-04-22
96,96,172,Neha Desai,HR,Chennai,22.000000,52250.0,0,5,7,2020-11-14
97,97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06
98,98,193,Priya Nayak,HR,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07
99,99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25

In [160]:
df['Annual_Salary'] = df['salary']*12

In [161]:
df.head()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary
0,0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0
1,1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0
2,2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0
3,3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0
4,4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0

In [162]:
def categorize(num):
    if num >= 5:
        return "Experience Candidate"
    elif num >= 3 and num <5:
        return "Junior Candidate"
    else:
        return "Fresher Candidate"

In [163]:
df['Experience_Category'] = df['experience'].apply(categorize)

In [164]:
df.tail()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary,Experience_Category
95,95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740.0,0,5,22,2020-04-22,668880.0,Fresher Candidate
96,96,172,Neha Desai,HR,Chennai,22.0,52250.0,0,5,7,2020-11-14,627000.0,Fresher Candidate
97,97,115,Neha Reddy,Marketing,Chennai,43.0,62969.5,12,4,10,2019-06-06,755634.0,Experience Candidate
98,98,193,Priya Nayak,HR,Hyderabad,23.0,56821.0,3,9,16,2019-08-07,681852.0,Junior Candidate
99,99,152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25,833988.0,Experience Candidate

In [165]:
df.sort_values(by = 'salary', ascending = False)

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary,Experience_Category
74,74,158,Tanvi Malhotra,Marketing,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experience Candidate
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experience Candidate
88,88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experience Candidate
84,84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experience Candidate
39,39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Fresher Candidate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,608796.0,Fresher Candidate
67,67,169,Swati Chatterjee,HR,Pune,33.0,49801.0,3,6,11,2021-08-20,597612.0,Junior Candidate
33,33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,596316.0,Fresher Candidate
36,36,167,Meera Malhotra,HR,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,585864.0,Junior Candidate
26,26,141,Manish Kulkarni,HR,Chennai,27.0,45835.0,3,8,13,2022-07-21,550020.0,Junior Candidate

In [166]:
df['department'] = df['department'].str.strip().str.title()
df['department'].unique()

array(['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing',
       'Finance'], dtype=object)

In [167]:
df.sort_values(by = ['department','salary'],ascending=[True,False])

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary,Experience_Category
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experience Candidate
88,88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experience Candidate
59,59,190,Swati Bose,Data Science,Mumbai,22.0,78465.0,0,8,18,2022-11-22,941580.0,Fresher Candidate
24,24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,917100.0,Experience Candidate
54,54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267.0,5,6,3,2023-01-24,915204.0,Experience Candidate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,48,163,Rahul Chatterjee,Sales,Kolkata,25.0,60015.0,0,8,9,2023-05-10,720180.0,Fresher Candidate
17,17,178,Vikram Kapoor,Sales,Chennai,29.0,57858.0,3,7,1,2020-06-26,694296.0,Junior Candidate
44,44,128,Rohan Chatterjee,Sales,Mumbai,26.0,52862.0,1,3,7,2022-08-04,634344.0,Fresher Candidate
38,38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12,630876.0,Experience Candidate
5,5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27,628848.0,Fresher Candidate

In [168]:
df.sort_values(by = 'department', ascending = False)

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary,Experience_Category
48,48,163,Rahul Chatterjee,Sales,Kolkata,25.0,60015.0,0,8,9,2023-05-10,720180.0,Fresher Candidate
38,38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12,630876.0,Experience Candidate
5,5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27,628848.0,Fresher Candidate
23,23,143,Neha Rao,Sales,Hyderabad,37.0,62969.5,11,6,11,2023-05-15,755634.0,Experience Candidate
87,87,103,Ananya Nayak,Sales,Delhi,38.0,68490.0,9,6,6,2021-11-19,821880.0,Experience Candidate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,20,156,Aditya Kapoor,Data Science,Kolkata,26.0,69765.0,0,2,4,2020-04-12,837180.0,Fresher Candidate
59,59,190,Swati Bose,Data Science,Mumbai,22.0,78465.0,0,8,18,2022-11-22,941580.0,Fresher Candidate
88,88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experience Candidate
22,22,127,Suresh Verma,Data Science,Bangalore,27.0,72862.0,2,6,10,2023-02-21,874344.0,Fresher Candidate
0,0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,Experience Candidate

In [169]:
df

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary,Experience_Category
0,0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0,Experience Candidate
1,1,154,Kavya Malhotra,Engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Fresher Candidate
2,2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0,Fresher Candidate
3,3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0,Junior Candidate
4,4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experience Candidate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,161,Nikhil Nair,Marketing,Chennai,22.000000,55740.0,0,5,22,2020-04-22,668880.0,Fresher Candidate
96,96,172,Neha Desai,Hr,Chennai,22.000000,52250.0,0,5,7,2020-11-14,627000.0,Fresher Candidate
97,97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06,755634.0,Experience Candidate
98,98,193,Priya Nayak,Hr,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07,681852.0,Junior Candidate
99,99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25,833988.0,Experience Candidate

In [170]:
df["salary_rank"] = df["salary"].rank(ascending = False)

In [171]:
df.sort_values("salary_rank")

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary,Experience_Category,salary_rank
74,74,158,Tanvi Malhotra,Marketing,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experience Candidate,1.0
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experience Candidate,2.0
88,88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experience Candidate,3.0
84,84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experience Candidate,4.0
39,39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Fresher Candidate,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,608796.0,Fresher Candidate,92.0
67,67,169,Swati Chatterjee,Hr,Pune,33.0,49801.0,3,6,11,2021-08-20,597612.0,Junior Candidate,93.0
33,33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,596316.0,Fresher Candidate,94.0
36,36,167,Meera Malhotra,Hr,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,585864.0,Junior Candidate,95.0
26,26,141,Manish Kulkarni,Hr,Chennai,27.0,45835.0,3,8,13,2022-07-21,550020.0,Junior Candidate,96.0

In [176]:
df['age'] = df['age'].astype(int)
df.nsmallest(5,"performance_score")

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Annual_Salary,Experience_Category,salary_rank
20,20,156,Aditya Kapoor,Data Science,Kolkata,26,69765.0,0,2,4,2020-04-12,837180.0,Fresher Candidate,29.0
24,24,170,Rahul Nair,Data Science,Kolkata,30,76425.0,5,2,4,2021-06-25,917100.0,Experience Candidate,14.0
50,50,125,Sneha Bose,Marketing,Mumbai,32,56627.0,7,2,9,2023-07-12,679524.0,Experience Candidate,77.0
76,76,176,Shreya Menon,Finance,Hyderabad,41,80597.0,9,2,18,2024-11-09,967164.0,Experience Candidate,7.0
12,12,174,Divya Chatterjee,Finance,Kolkata,24,58374.0,1,3,12,2018-09-21,700488.0,Fresher Candidate,71.0

In [180]:
df.groupby('department')['salary'].max().astype(int)

department
Data Science    88216
Engineering     84870
Finance         80597
Hr              66363
Marketing       88366
Sales           68490
Name: salary, dtype: int64

In [181]:
df.groupby(['city','department'])['salary'].max()

city       department
Bangalore  Data Science    72862.0
           Engineering     81112.0
           Finance         71062.0
           Hr              59591.0
           Marketing       74505.0
Chennai    Engineering     77222.0
           Finance         71889.0
           Hr              52250.0
           Marketing       62969.5
           Sales           57858.0
Delhi      Data Science    76267.0
           Engineering     80358.0
           Finance         66422.0
           Hr              66363.0
           Marketing       69499.0
           Sales           68490.0
Hyderabad  Data Science    88216.0
           Engineering     84870.0
           Finance         80597.0
           Hr              59895.0
           Marketing       69076.0
           Sales           62969.5
Kolkata    Data Science    76425.0
           Engineering     84255.0
           Finance         59422.0
           Hr              59693.0
           Marketing       59186.0
           Sales           60015.0
Mumbai     Data Science    78465.0
           Engineering     77058.0
           Finance         64112.0
           Marketing       88366.0
           Sales           52862.0
Pune       Data Science    75498.0
           Engineering     78545.0
           Finance         62020.0
           Hr              56504.0
           Marketing       68197.0
Name: salary, dtype: float64

In [182]:
df.to_csv("employees_100_cleaned.csv", index=False)